export const data = [
    { id: 1, name: 'John Smith', age: 32, salary: 60000, department: 'IT', position: 'Developer' },
    { id: 2, name: 'Jane Doe', age: 28, salary: 55000, department: 'IT', position: 'Developer' },
    { id: 3, name: 'Alex Johnson', age: 35, salary: 80000, department: 'IT', position: 'Manager' },
    { id: 4, name: 'Emily White', age: 40, salary: 90000, department: 'IT', position: 'Manager' },
    { id: 5, name: 'Michael Brown', age: 45, salary: 100000, department: 'IT', position: 'Director' },
    { id: 6, name: 'Laura Davis', age: 50, salary: 120000, department: 'IT', position: 'Director' },
    { id: 7, name: 'William Miller', age: 55, salary: 150000, department: 'IT', position: 'CEO' },
    { id: 8, name: 'Sophia Wilson', age: 60, salary: 180000, department: 'IT', position: 'CEO' },
    { id: 9, name: 'Ethan Taylor', age: 65, salary: 200000, department: 'IT', position: 'CEO' },
    { id: 10, name: 'Olivia Martinez', age: 70, salary: 220000, department: 'IT', position: 'CEO' },
    { id: 11, name: 'Daniel Anderson', age: 75, salary: 250000, department: 'IT', position: 'CEO' },
    { id: 12, name: 'Ava Garcia', age: 80, salary: 280000, department: 'IT', position: 'CEO' },
    { id: 13, name: 'Henry Hernandez', age: 85, salary: 300000, department: 'IT', position: 'CEO' },
    { id: 14, name: 'Sofia Lee', age: 90, salary: 320000, department: 'IT', position: 'CEO' },
    { id: 15, name: 'Liam Rodriguez', age: 95, salary: 350000, department: 'IT', position: 'CEO' },
    { id: 16, name: 'Emma Kim', age: 100, salary: 380000, department: 'IT', position: 'CEO' },
    { id: 17, name: 'Benjamin Nguyen', age: 105, salary: 400000, department: 'IT', position: 'CEO' },
    { id: 18, name: 'Mia Patel', age: 110, salary: 420000, department: 'IT', position: 'CEO' },
    { id: 19, name: 'Sebastian Smith', age: 115, salary: 450000, department: 'IT', position: 'CEO' },
    { id: 20, name: 'Aria Wang', age: 120, salary: 480000, department: 'IT', position: 'CEO' },
    { id: 21, name: 'Jackson Chen', age: 125, salary: 500000, department: 'IT', position: 'CEO' },
  ];
  